name: deploy 
on:
    pull_request: 
        types:
            - closed
jobs:
    on_merge: 
        runs-on: ubuntu-latest  
        if: github.event.pull_request.merged == true
        steps:
            - uses: actions/checkout@v2 
            - run: echo "Pull request merged"